/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.jena.examples.tdbont; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from /Users/benson/x/oap/common/src/main/resources/com/basistech/jug/ontologies/rex.owl 
 * @author Auto-generated by schemagen on 10 Dec 2010 15:56 
 */
public class Rex {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.basistech.com/ontologies/2010/6/rex.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty corefLink = m_model.createObjectProperty( "http://www.basistech.com/ontologies/2010/6/rex.owl#corefLink" );
    
    public static final ObjectProperty crossdocCorefLink = m_model.createObjectProperty( "http://www.basistech.com/ontologies/2010/6/rex.owl#crossdocCorefLink" );
    
    public static final ObjectProperty indocCorefLink = m_model.createObjectProperty( "http://www.basistech.com/ontologies/2010/6/rex.owl#indocCorefLink" );
    
    /** <p>A reference to the URI of the document where something was discovered.</p> */
    public static final DatatypeProperty hasContainingDocument = m_model.createDatatypeProperty( "http://www.basistech.com/ontologies/2010/6/rex.owl#hasContainingDocument" );
    
    /** <p>This property is set on entity references that are tagged with a user-defined 
     *  type.</p>
     */
    public static final DatatypeProperty hasCustomEntityType = m_model.createDatatypeProperty( "http://www.basistech.com/ontologies/2010/6/rex.owl#hasCustomEntityType" );
    
    /** <p>The source of the reference.</p> */
    public static final DatatypeProperty hasEntityDetectionSource = m_model.createDatatypeProperty( "http://www.basistech.com/ontologies/2010/6/rex.owl#hasEntityDetectionSource" );
    
    /** <p>Normalized text of an entity reference</p> */
    public static final DatatypeProperty hasNormalizedText = m_model.createDatatypeProperty( "http://www.basistech.com/ontologies/2010/6/rex.owl#hasNormalizedText" );
    
    /** <p>The original text of a reference.</p> */
    public static final DatatypeProperty hasOriginalText = m_model.createDatatypeProperty( "http://www.basistech.com/ontologies/2010/6/rex.owl#hasOriginalText" );
    
    public static final OntClass CreditCardNumber = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#CreditCardNumber" );
    
    public static final OntClass Date = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Date" );
    
    public static final OntClass Distance = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Distance" );
    
    public static final OntClass DomainName = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#DomainName" );
    
    public static final OntClass Email = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Email" );
    
    public static final OntClass EntityReference = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#EntityReference" );
    
    public static final OntClass Facility = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Facility" );
    
    public static final OntClass FaxNumber = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#FaxNumber" );
    
    public static final OntClass GeoLocation = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#GeoLocation" );
    
    public static final OntClass IPAddress = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#IPAddress" );
    
    public static final OntClass Identifier = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Identifier" );
    
    public static final OntClass LatitudeLongitude = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#LatitudeLongitude" );
    
    public static final OntClass Location = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Location" );
    
    public static final OntClass Money = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Money" );
    
    public static final OntClass Nationality = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Nationality" );
    
    public static final OntClass Number = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Number" );
    
    public static final OntClass Organization = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Organization" );
    
    public static final OntClass Percent = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Percent" );
    
    public static final OntClass Person = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Person" );
    
    public static final OntClass PersonalIdNumber = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#PersonalIdNumber" );
    
    public static final OntClass Quantity = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Quantity" );
    
    public static final OntClass Religion = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Religion" );
    
    public static final OntClass TelephoneNumber = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#TelephoneNumber" );
    
    public static final OntClass Temporal = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Temporal" );
    
    public static final OntClass Time = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Time" );
    
    public static final OntClass URL = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#URL" );
    
    public static final OntClass USA_SSN = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#USA_SSN" );
    
    public static final OntClass UTM = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#UTM" );
    
    public static final OntClass Vehicle = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Vehicle" );
    
    public static final OntClass Weapon = m_model.createClass( "http://www.basistech.com/ontologies/2010/6/rex.owl#Weapon" );
    
}
